### ISSUE TITLE
Is giving-me a error on startup.

### ISSUE THREAD

**Issue by FutonGama** [w-e-w/sd-webui-hires-fix-tweaks#2]
![image](https://github.com/w-e-w/sd-webui-hires-fix-tweaks/assets/95169493/d4bc68d7-dfd7-4d86-a28d-6885e3aa05e6)
Is giving-me a error on startup, commit 682a1b3 is not giving error, the startup problem starts on commit 9b2e349, commits before this one works.
I know is in development and i'm just informing the problems. Take your time. Thanks for the extension, excellent work :)

**Comment by w-e-w** [comment]
thanks

should be fixed 32bf1b577bb73c7f820c4b636864de0a40496cc6 now

**Comment by FutonGama** [comment]
Thanks!!
