### ISSUE TITLE
[Feature Request] Remove Styles checkbox

### ISSUE THREAD

**Issue by StylusEcho** [w-e-w/sd-webui-hires-fix-tweaks#7]
Should function similarly to the existing Remove First Pass extra networks toggle, except it removes the styles that were applied to the first pass. This would be good if for example, styles were used that included quality tags, but would be detrimental when used with the particular checkpoint chosen for Hires fix.

**Comment by w-e-w** [comment]
care for some beta testing?
https://github.com/w-e-w/sd-webui-hires-fix-tweaks/tree/Hires-Styles
![image](https://github.com/user-attachments/assets/46084bde-6369-4285-ad9e-f50c942a7004)

**Comment by StylusEcho** [comment]
Sorry, I get so many emails from Github, I missed this. Thanks, I'll test it very soon!

**Comment by StylusEcho** [comment]
Hey, from my testing, it seems to all work as expected, and the implementation is easy to understand. Great work!

**Comment by w-e-w** [comment]
thanks for testing
merged to main
