### ISSUE TITLE
Feature Request - Add Path to Checkpoint Dropdown

### ISSUE THREAD

**Issue by Wprussell** [w-e-w/sd-webui-hires-fix-tweaks#9]
Please add Path to the Checkpoint Dropdown 

For those of us that have OCD or Have a Billion checkpoints organized by path. either/or. 

TY

**Comment by w-e-w** [comment]
- I made it possible in https://github.com/w-e-w/sd-webui-hires-fix-tweaks/commit/d03c8b67fee16f45da95ace577f3a36e7ac89d73

![image](https://github.com/user-attachments/assets/ccb4bfce-e3ab-4a95-bd77-1da6c20b84ad)

**Comment by w-e-w** [comment]
out of curiosity how much checkpoints do you have?

**Comment by Wprussell** [comment]
Ok, you got me...

Lest than a billion.- however, lots of merges, sorry a few hundred organized by dir.

And Thank you.

**Comment by Wprussell** [comment]
On a side note, went through some kudos. 
This investigation all started while trying to apply the proper checkpoint to hiresfix with refiner. See the following thread.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12810

Thanks again...

Cruel_world
